// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsLsAv2kgLJmcaNV6lFXG_YXhP7zefZN4',
    appId: '1:1011733196768:web:8c593d526e587eee8f4585',
    messagingSenderId: '1011733196768',
    projectId: 'scoreapp-87d8a',
    authDomain: 'scoreapp-87d8a.firebaseapp.com',
    storageBucket: 'scoreapp-87d8a.firebasestorage.app',
    measurementId: 'G-DT0PM067P9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqSNaMxhenJzhR23D6jj8N63lPfQyoieA',
    appId: '1:1011733196768:android:5e9c6cf95570a36f8f4585',
    messagingSenderId: '1011733196768',
    projectId: 'scoreapp-87d8a',
    storageBucket: 'scoreapp-87d8a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX5_itQNwn0vVHoHHs2MUH0sb8CZU84lM',
    appId: '1:1011733196768:ios:d82a713dcc26782e8f4585',
    messagingSenderId: '1011733196768',
    projectId: 'scoreapp-87d8a',
    storageBucket: 'scoreapp-87d8a.firebasestorage.app',
    androidClientId: '1011733196768-pvbpaqvhj412kbtjiuepspd37kfmg8od.apps.googleusercontent.com',
    iosClientId: '1011733196768-cftb22e9pdk84mu1b5d1fqrtmfs8nj7j.apps.googleusercontent.com',
    iosBundleId: 'com.example.scoringApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX5_itQNwn0vVHoHHs2MUH0sb8CZU84lM',
    appId: '1:1011733196768:ios:d82a713dcc26782e8f4585',
    messagingSenderId: '1011733196768',
    projectId: 'scoreapp-87d8a',
    storageBucket: 'scoreapp-87d8a.firebasestorage.app',
    androidClientId: '1011733196768-pvbpaqvhj412kbtjiuepspd37kfmg8od.apps.googleusercontent.com',
    iosClientId: '1011733196768-cftb22e9pdk84mu1b5d1fqrtmfs8nj7j.apps.googleusercontent.com',
    iosBundleId: 'com.example.scoringApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsLsAv2kgLJmcaNV6lFXG_YXhP7zefZN4',
    appId: '1:1011733196768:web:b66d18feb212480a8f4585',
    messagingSenderId: '1011733196768',
    projectId: 'scoreapp-87d8a',
    authDomain: 'scoreapp-87d8a.firebaseapp.com',
    storageBucket: 'scoreapp-87d8a.firebasestorage.app',
    measurementId: 'G-VRGQ8MNQRL',
  );

}